version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shop_management_api_getway
    volumes:
      - ./uploads:/app/uploads
    environment:
      - DATABASE_URL=postgresql://postgres:lelamtuan@shop-management-instance.c7cs0m28m6l4.ap-southeast-2.rds.amazonaws.com:5432/shop_management_api_getway?schema=public
      - AT_SECRET=JuSHiHN+u2UDGTKwM82cblUh2Z7bBiAs
      - RT_SECRET=WsesiMfifQm5OKuXv4AtVNi3MR6AjubY
      - RESET_SECRET=TlqoBpBiZNbTYrSb
      - SENDER_EMAIL=ltpg2594gm@gmail.com
      - SENDER_PASSWORD="xvxe tsqn asag cpyh"
      - BASE_URL=http://3.27.63.149:8080
      - FE_BASE_URL="http://localhost:3000"
      - API_BASE_PREFIX=api/v1
      - AMQP_PRODUCT_URL=amqps://qahaacnd:n_MMhZWIfeGnc88PZl2dXUbXBouqSfBa@armadillo.rmq.cloudamqp.com/qahaacnd
      - AMQP_ORDER_URL=amqps://lyhwedur:p0xoHlnGxtV0Z60p5mKpizY0Ow3QEZ36@armadillo.rmq.cloudamqp.com/lyhwedur
    ports:
      - '8080:8080'
    restart: 'always'
